package com.todo.dao;

import com.todo.model.Todo;
import java.util.List;

/**
 * TodoDAO Interface (Data Access Object)
 * 
 * DAO Pattern: Separates the data access logic from business logic
 * This interface defines WHAT operations we can perform on Todo data
 * The implementation class (TodoDAOImpl) will define HOW to perform these
 * operations
 * 
 * Why use an interface?
 * - Loose coupling: Service layer depends on interface, not implementation
 * - Easy to test: Can create mock implementations for testing
 * - Flexibility: Can switch database implementations without changing service
 * layer
 * - Following SOLID principles (Dependency Inversion Principle)
 */
public interface TodoDAO {

    /**
     * CREATE operation - Add a new todo to the database
     * 
     * @param todo - The Todo object to be inserted into database
     *             (id will be auto-generated by database)
     */
    void create(Todo todo);

    /**
     * READ operation - Find a specific todo by its ID
     * 
     * @param id - The unique identifier of the todo to find
     * @return The Todo object if found, null if not found
     */
    Todo findById(int id);

    /**
     * READ operation - Get all todos from the database
     * 
     * @return A List containing all Todo objects
     *         Returns empty list if no todos exist
     */
    List<Todo> findAll();

    /**
     * UPDATE operation - Modify an existing todo in the database
     * 
     * @param todo - The Todo object with updated values
     *             (must have a valid id that exists in database)
     */
    void update(Todo todo);

    /**
     * DELETE operation - Remove a todo from the database
     * 
     * @param id - The unique identifier of the todo to delete
     */
    void delete(int id);

    /**
     * Additional query - Find todos by completion status
     * This demonstrates how to add custom query methods
     * 
     * @param completed - true to find completed todos, false for incomplete
     * @return List of todos matching the completion status
     */
    List<Todo> findByCompleted(boolean completed);
}
