package com.todo.model;

/**
 * Todo Model Class (Entity/POJO - Plain Old Java Object)
 * 
 * This class represents a single Todo item in our application.
 * It's a simple Java class with private fields and public getter/setter
 * methods.
 * 
 * In Spring Core (without JPA), this is just a regular Java class that maps to
 * our database table.
 * Each field in this class corresponds to a column in the 'todos' table.
 */
public class Todo {

    // ========== FIELDS (Properties) ==========
    // These represent the columns in our database table

    /**
     * Unique identifier for each todo item
     * Maps to 'id' column in database (PRIMARY KEY, AUTO_INCREMENT)
     */
    private int id;

    /**
     * Title/name of the todo item
     * Maps to 'title' column in database (VARCHAR(255), NOT NULL)
     */
    private String title;

    /**
     * Detailed description of the todo item
     * Maps to 'description' column in database (TEXT)
     */
    private String description;

    /**
     * Status of the todo - whether it's completed or not
     * Maps to 'completed' column in database (BOOLEAN, DEFAULT FALSE)
     */
    private boolean completed;

    // ========== CONSTRUCTORS ==========

    /**
     * Default Constructor (No arguments)
     * Required for frameworks like Spring to create instances of this class
     */
    public Todo() {
        // Empty constructor - Spring will use this to create objects
    }

    /**
     * Constructor with all fields (except id)
     * Used when creating a new Todo item (id will be auto-generated by database)
     * 
     * @param title       - The title of the todo
     * @param description - The description of the todo
     * @param completed   - Whether the todo is completed
     */
    public Todo(String title, String description, boolean completed) {
        this.title = title;
        this.description = description;
        this.completed = completed;
    }

    /**
     * Constructor with all fields (including id)
     * Used when retrieving existing Todo items from database
     * 
     * @param id          - The unique identifier
     * @param title       - The title of the todo
     * @param description - The description of the todo
     * @param completed   - Whether the todo is completed
     */
    public Todo(int id, String title, String description, boolean completed) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.completed = completed;
    }

    // ========== GETTERS AND SETTERS ==========
    // These methods allow us to access and modify the private fields
    // This follows the JavaBean convention

    /**
     * Get the id of this todo
     * 
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * Set the id of this todo
     * 
     * @param id - the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Get the title of this todo
     * 
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Set the title of this todo
     * 
     * @param title - the title to set
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Get the description of this todo
     * 
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Set the description of this todo
     * 
     * @param description - the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Check if this todo is completed
     * 
     * @return true if completed, false otherwise
     */
    public boolean isCompleted() {
        return completed;
    }

    /**
     * Set the completion status of this todo
     * 
     * @param completed - true to mark as completed, false otherwise
     */
    public void setCompleted(boolean completed) {
        this.completed = completed;
    }

    // ========== UTILITY METHODS ==========

    /**
     * String representation of this Todo object
     * Useful for debugging and printing
     * 
     * @return A formatted string with all todo details
     */
    @Override
    public String toString() {
        return "Todo{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", completed=" + completed +
                '}';
    }
}
